version: '3.3'
services:
  db:
    build: ./docker/postgresql
#    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: sample
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: sample
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=ja_JP.UTF-8"
    command: 'postgres -c config_file="/etc/postgresql/postgresql.conf"'
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/postgresql/conf.d:/etc/postgresql
      - ./log/postgresql:/var/log/postgresql
